{% set name = "pak_unior" %}
{% set version = "1.2.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: bf8059d27518d25d00e2927931ca378ab898f7b600ab6359319c3f74f6bbbd60

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  build:
    - python
    - setuptools
    - conda
    - pip

  host:
    - pip
    - python
    - conda
  run:
    - python
  script: conda create --name pak_unior_env --file spec-file.txt

about:
  home: The package home page
  license: OSL
  license_family: OTHER
  license_file: 
  summary: "PAK UNIOR web plot"
  doc_url: https://pypi.python.org/pypi/pak_unior/
  dev_url: https://github.com/ArtyomZemlyak/pak_unior

extra:
  recipe-maintainers:
    - https://github.com/ArtyomZemlyak
