{% set name = "pak_unior" %}
{% set version = "1.2.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4b06d8dec3f983715f276a45256851052794de3d5f357a953b52637dd8da296a

build:
  number: 0
  script: conda env create -f environment.yml

about:
  home: The package home page
  license: OSL
  license_family: OTHER
  license_file: 
  summary: "PAK UNIOR web plot"
  doc_url: https://pypi.python.org/pypi/pak_unior/
  dev_url: https://github.com/ArtyomZemlyak/pak_unior

extra:
  recipe-maintainers:
    - https://github.com/ArtyomZemlyak
