{% set name = "pak_unior" %}
{% set version = "1.2.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 11ae3b503d704bbe8f7995c2195d3ff7a9ff25e7479e10fba0758e48093e41f3

build:
  number: 0
  script: "conda env create -f environment.yml"

about:
  home: The package home page
  license: OSL
  license_family: OTHER
  license_file: 
  summary: "PAK UNIOR web plot"
  doc_url: https://pypi.python.org/pypi/pak_unior/
  dev_url: https://github.com/ArtyomZemlyak/pak_unior

extra:
  recipe-maintainers:
    - https://github.com/ArtyomZemlyak
